# Generated by Django 2.0.7 on 2018-07-03 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userno', models.CharField(db_index=True, max_length=11, unique=True)),
                ('username', models.CharField(db_index=True, max_length=32)),
                ('is_first_login', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('role', models.IntegerField(choices=[(1, '学生'), (2, '教师'), (3, '教务')])),
                ('college', models.IntegerField(
                    choices=[(1, '新闻学院'), (2, '信息工程学院'), (3, '马克思研究学院'), (4, '医学院'), (5, '播音学院'), (6, '戏剧影视学院'),
                             (7, '计算机学院'), (8, '外国语学院')], null=True)),
                ('card_id', models.CharField(max_length=18)),
                ('nation', models.IntegerField(
                    choices=[(1, '汉族'), (2, '回族'), (3, '壮族'), (4, '蒙古族'), (5, '朝鲜族'), (6, '满族'), (7, '客家族'),
                             (8, '维吾尔族'), (9, '藏族'), (10, '傣族')])),
                ('province', models.IntegerField(
                    choices=[(1, '北京市'), (2, '天津市'), (3, '上海市'), (4, '重庆市'), (5, '河北省'), (6, '山西省'), (7, '辽宁省'),
                             (8, '吉林省'), (9, '黑龙江省'), (10, '江苏省'), (11, '浙江省'), (12, '安徽省'), (13, '福建省'), (14, '江西省'),
                             (15, '山东省'), (16, '河南省'), (17, '湖北省'), (18, '湖南省'), (19, '广东省'), (20, '海南省'), (21, '四川省'),
                             (22, '贵州省'), (23, '云南省'), (24, '陕西省'), (25, '甘肃省'), (26, '青海省'), (27, '台湾省'),
                             (28, '内蒙古自治区'), (29, '广西壮族自治区'), (30, '西藏自治区'), (31, '宁夏回族自治区'), (32, '新疆维吾尔自治区'),
                             (33, '香港特别行政区'), (34, '澳门特别行政区')])),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=11)),
                ('avatar', models.ImageField(default=None, null=True, upload_to='user_avatar')),
                ('birthday', models.DateTimeField()),
                ('qq', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Grade'),
        ),
    ]
