# Generated by Django 2.0.7 on 2018-07-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180703_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userno',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='user_no', db_index=True, max_length=11, unique=True),
        ),
    ]
