# Generated by Django 2.0.7 on 2018-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180703_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_id',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='nation',
            field=models.IntegerField(choices=[(1, '汉族'), (2, '回族'), (3, '壮族'), (4, '蒙古族'), (5, '朝鲜族'), (6, '满族'), (7, '客家族'), (8, '维吾尔族'), (9, '藏族'), (10, '傣族')], null=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.IntegerField(choices=[(1, '北京市'), (2, '天津市'), (3, '上海市'), (4, '重庆市'), (5, '河北省'), (6, '山西省'), (7, '辽宁省'), (8, '吉林省'), (9, '黑龙江省'), (10, '江苏省'), (11, '浙江省'), (12, '安徽省'), (13, '福建省'), (14, '江西省'), (15, '山东省'), (16, '河南省'), (17, '湖北省'), (18, '湖南省'), (19, '广东省'), (20, '海南省'), (21, '四川省'), (22, '贵州省'), (23, '云南省'), (24, '陕西省'), (25, '甘肃省'), (26, '青海省'), (27, '台湾省'), (28, '内蒙古自治区'), (29, '广西壮族自治区'), (30, '西藏自治区'), (31, '宁夏回族自治区'), (32, '新疆维吾尔自治区'), (33, '香港特别行政区'), (34, '澳门特别行政区')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
