# Generated by Django 2.0.7 on 2018-07-04 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20180703_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.IntegerField(blank=True, choices=[(1, '新闻学院'), (2, '信息工程学院'), (3, '马克思研究学院'), (4, '医学院'), (5, '播音学院'), (6, '戏剧影视学院'), (7, '计算机学院'), (8, '外国语学院')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.IntegerField(blank=True, choices=[(1, '助教'), (2, '讲师'), (3, '高级讲师'), (4, '副教授'), (5, '教授'), (6, '高级教授'), (7, '特聘教授'), (8, '客座教授')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, '学生'), (2, '教师'), (3, '教务')], null=True),
        ),
    ]
