# Generated by Django 2.0.7 on 2018-07-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180709_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qq',
            new_name='QQ',
        ),
    ]
