# Generated by Django 2.0.7 on 2018-07-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180704_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='mtime',
            field=models.DateTimeField(null=True),
        ),
    ]
