# Generated by Django 2.0.7 on 2018-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180703_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_close_time',
            field=models.DateTimeField(default='2018-06-30 23:50:50'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_online_time',
            field=models.DateTimeField(default='2018-06-30 23:06:06'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_online',
            field=models.BooleanField(default=False),
        ),
    ]
