# Generated by Django 2.0.7 on 2018-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180704_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_college',
            field=models.IntegerField(choices=[(1, '新闻学院'), (2, '信息工程学院'), (3, '马克思研究学院'), (4, '医学院'), (5, '播音学院'), (6, '戏剧影视学院'), (7, '计算机学院'), (8, '外国语学院')], null=True),
        ),
    ]
