# Generated by Django 2.0.7 on 2018-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20180704_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_choosed',
            field=models.BooleanField(default=False),
        ),
    ]
