# Generated by Django 2.0.7 on 2018-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20180704_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_choosed',
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='is_choosed',
            field=models.BooleanField(default=True),
        ),
    ]
