# Generated by Django 2.0.7 on 2018-07-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20180706_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_choosed',
            field=models.BooleanField(default=False),
        ),
    ]
