# Generated by Django 2.0.7 on 2018-07-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_studentcourse_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_total_people',
            field=models.IntegerField(null=True),
        ),
    ]
