# Generated by Django 2.0.7 on 2018-07-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20180706_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_choosed',
        ),
        migrations.AddField(
            model_name='course',
            name='course_total_student',
            field=models.IntegerField(default=0),
        ),
    ]
