# Generated by Django 2.0.7 on 2018-07-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20180706_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_total_student',
            new_name='course_choosed_student',
        ),
    ]
