# Generated by Django 2.0.7 on 2018-07-07 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0018_auto_20180706_1953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_teacher', 'course_week', 'course_time', 'course_classroom')},
        ),
    ]
