# Generated by Django 2.0.7 on 2018-07-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0023_auto_20180707_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_visable',
            field=models.BooleanField(default=True),
        ),
    ]
