# Generated by Django 2.0.7 on 2018-07-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_auto_20180710_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.IntegerField(choices=[(1, '专业课'), (2, '公选课')], null=True),
        ),
    ]
